### ISSUE TITLE
Dependent Events don't work as intended. 

### ISSUE THREAD

**Issue by Ftyari** [Maruno17/pokemon-essentials#45] opened 2020-10-21 21:47 UTC
Dependent events are bugged, and the event that is supposed to go with the player doesn't. For some reason, if you have an old enough save file, dependent events work just fine. Also, when dependent events do work, if the player moves before the dependent event is finished hopping down a ledge, the dependent event goes spastic; this continues until the player decides to stop moving.

How to produce: I don't actually know the exact trigger. I just started a new game on a vanilla fork of the GitHub, and the dependency event just didn't work on that save file. For some reason, it worked with the older save file. I have no idea why. It's literally the exact same game, same scripts, etc.

The problem if you start a new game/have a save file that isn't old enough: https://i.imgur.com/tB5fhdc.gifv
The dependent event working in an old save file, but spazzing out when going down ledges: https://i.imgur.com/gkSM8lG.gifv

The partner trainer does show up in battle, though.

**Comment by Maruno17** [comment] 2020-10-23 20:19
I've just pushed a fix for the dependent events disappearing instead of following you. The `dependentEvents` array wasn't being created properly.

As far as ledges go, the problem is that an event/player moves at walking speed while jumping over a ledge, meaning the player could run away while the following event is still jumping, resulting in the event making illegal moves to try to catch up to the player. Since a ledge jump involves travelling two tiles, the dependent event's jump would need to be twice as fast as the player's movement speed away from the bottom of the ledge (whether they're walking or running) to keep up - this is what the following mon does in HGSS. It's inelegant but it's the only way to avoid problems.

As far as implementing this behaviour, I personally won't. I'm not familiar with the dependent event scripts, aside from knowing that they'd benefit from a complete rewrite, so I'm happy to put this fix off until that happens. Everywhere in DPPt where the player is accompanied by another trainer, there are no ledges to jump over (thus avoiding this problem), so my advice is to not mix followers with ledges, at least for now.

**Comment by Maruno17** [comment] 2021-01-03 13:51
I've just pushed a fix for the ledge jumping speed. Dependent events now perform the whole jump in the same time the player takes to make their next move (a la HGSS). It makes for super-fast jumps (if the player isn't immediately making another jump), but at least the dependent event keeps up now.

I've also fixed dependent events not always looking where they're going, i.e. turning to face the player at the start of a step rather than at the end.

**Closed by Maruno17** 2021-01-03 13:51 UTC
